# Generated by Django 6.0.1 on 2026-07-04 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.CharField(editable=False, max_length=24, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('auction_type', models.CharField(choices=[('in_person', 'Auction In Person'), ('online', 'Online Auction'), ('hybrid', 'Hybrid Auction')], default='in_person', max_length=24)),
                ('number_of_teams', models.PositiveIntegerField(default=0)),
                ('allotted_to_user', models.CharField(blank=True, max_length=150)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('setup', 'Setup'), ('active', 'Active'), ('live', 'Live'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('logo_url', models.URLField(blank=True)),
                ('unit', models.CharField(default='INR', max_length=24)),
                ('purse_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=100000, max_digits=14)),
                ('timer_duration', models.PositiveIntegerField(default=30)),
                ('minimum_players_per_team', models.PositiveIntegerField(default=0)),
                ('maximum_players_per_team', models.PositiveIntegerField(default=0)),
                ('sold_animation_state', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_auctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='auctions.auction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_remaining_purse', models.BooleanField(default=True)),
                ('require_bid_approval', models.BooleanField(default=True)),
                ('auto_advance_after_sale', models.BooleanField(default=False)),
                ('sponsor_rotation_seconds', models.PositiveIntegerField(default=8)),
                ('public_screen_theme', models.CharField(default='purple_glow', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='auctions.auction')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(editable=False, max_length=24)),
                ('name', models.CharField(max_length=120)),
                ('minimum_players', models.PositiveIntegerField(default=0)),
                ('maximum_players', models.PositiveIntegerField(default=0)),
                ('base_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('color', models.CharField(default='#7C3AED', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.auction')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(editable=False, max_length=24)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('full_name', models.CharField(blank=True, max_length=180)),
                ('image_url', models.URLField(blank=True)),
                ('role', models.CharField(choices=[('Batter', 'Batter'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder'), ('Wicket-keeper', 'Wicket-keeper')], default='Batter', max_length=32)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('age', models.PositiveIntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('extra_field_1', models.CharField(blank=True, max_length=160)),
                ('extra_field_2', models.CharField(blank=True, max_length=160)),
                ('extra_field_3', models.CharField(blank=True, max_length=160)),
                ('extra_field_4', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_auction', 'In Auction'), ('sold', 'Sold'), ('unsold', 'Unsold')], default='available', max_length=16)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('queue_order', models.PositiveIntegerField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='auctions.auction')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='auctions.category')),
            ],
            options={
                'ordering': ['queue_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auctions.player'),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='auctions.auction')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(editable=False, max_length=24)),
                ('name', models.CharField(max_length=140)),
                ('short_name', models.CharField(max_length=16)),
                ('logo_url', models.URLField(blank=True)),
                ('owner_name', models.CharField(blank=True, max_length=140)),
                ('owner_username', models.CharField(blank=True, max_length=150)),
                ('purse_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remaining_purse', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('players_bought', models.PositiveIntegerField(default=0)),
                ('maximum_players', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='auctions.auction')),
                ('owner_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoldPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sold_time', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_players', to='auctions.auction')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sold_record', to='auctions.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_players', to='auctions.team')),
            ],
            options={
                'ordering': ['-sold_time'],
            },
        ),
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('auction_manager', 'Auction Manager'), ('team_owner', 'Team Owner')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles', to='auctions.auction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to=settings.AUTH_USER_MODEL)),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profile', to='auctions.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='sold_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='auctions.team'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bid_type', models.CharField(choices=[('manual', 'Manual'), ('team_owner', 'Team Owner')], max_length=16)),
                ('bid_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bids', to=settings.AUTH_USER_MODEL)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=140)),
                ('username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_owners', to='auctions.auction')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner_record', to='auctions.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('auction', 'category_id'), name='unique_category_code_per_auction'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('auction', 'name'), name='unique_category_name_per_auction'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('auction', 'team_id'), name='unique_team_code_per_auction'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('auction', 'short_name'), name='unique_team_short_per_auction'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('auction', 'player_id'), name='unique_player_code_per_auction'),
        ),
    ]
