# Generated by Django 6.0.1 on 2026-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
        ),
    ]
