# Generated by Django 5.2.16 on 2026-09-11 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_projectlogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField()),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='auctions.auction')),
            ],
            options={
                'ordering': ['revision'],
                'indexes': [models.Index(fields=['auction', 'revision'], name='event_auc_revision_idx'), models.Index(fields=['auction', 'created_at'], name='event_auc_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('auction', 'revision'), name='unique_event_revision_per_auction'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('auction', 'idempotency_key'), name='unique_event_idempotency_per_auction')],
            },
        ),
    ]
